# Generated by Django 3.2.13 on 2022-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('attack_date', models.DateTimeField(auto_now_add=True)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
